api/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'api'
urlpatterns = [
    path('request', TemplateView.as_view(template_name='api/request.html'), name='request'),
    path('predict', views.predict, name='predict'),
    path('predict2', views.predict2, name='predict2'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from api import views
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', TemplateView.as_view(template_name='api/request.html'), name='home'),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models


class Photo(models.Model):
    title = models.CharField(max_length=100)  # this field does not use in your project
    img = models.ImageField(upload_to='img/')

    def __str__(self):
        return self.title

api/forms.py
from django import forms


class UploadForm(forms.Form):
    upimg = forms.ImageField()

api/views.py
import os
import json
import numpy as np
import cv2
from time import time
from PIL import Image
from django.http import HttpResponse, FileResponse
from django.views.decorators.csrf import csrf_exempt
from config import settings
from . import forms, functions, func_ver2
from .apps import ApiConfig
from django.shortcuts import render
from django.http import FileResponse
from django.shortcuts import render
from .models import *
import random
import io
import base64

# ver.1
# @csrf_exempt # form post 요청을 받을 때 csrf 토큰없이 요청할 수 있도록 처리.
# def predict(request):
#     # 요청파라미터 - text: request.POST, file: request.FILES
#     form = forms.UploadForm(request.POST, request.FILES)
#     if form.is_valid(): #요청파라미터 검증. True: 검증 성공, False: 검증 실패
#         clean_data = form.cleaned_data #Form에서 직접 값을 조회할 수 없다. form.cleaned_data: 검증을 통과한 
#                                        #요청파라미터들을 딕셔너리로 반환. 이 딕셔너리를 이용해 조회
#         img_field  = clean_data['upimg'] #업로드된 파일을 조회
        
#         print(img_field, type(img_field))
#         print(img_field.image.width, img_field.image.height, img_field.image.format, img_field.name) #ImageField.name: 파일명

#         image = Image.open(img_field) # 이미지 로딩
#         image_arr = np.array(image)
#         model = ApiConfig.model
#         eng_model = ApiConfig.eng_model
#         result, blur_img, pre_result = functions.result_look(image_arr, model, eng_model)
        
#         img = Image.fromarray(cv2.cvtColor(blur_img, cv2.COLOR_BGR2RGB))
#         img = img.resize((410, 260))
#         blur_url = './img/img/blur'+str(random.random())+'.jpg'
#         img.save(blur_url)
#         result['url'] = blur_url[1:]
#         result['pre_result'] = [i[2] for i in pre_result]
        
#         return HttpResponse(json.dumps(result))

# ver.2
@csrf_exempt # form post 요청을 받을 때 csrf 토큰없이 요청할 수 있도록 처리.
def predict(request):
    start_time = time()
    # 요청파라미터 - text: request.POST, file: request.FILES
    form = forms.UploadForm(request.POST, request.FILES)
    if form.is_valid(): #요청파라미터 검증. True: 검증 성공, False: 검증 실패
        clean_data = form.cleaned_data #Form에서 직접 값을 조회할 수 없다. form.cleaned_data: 검증을 통과한 
                                       #요청파라미터들을 딕셔너리로 반환. 이 딕셔너리를 이용해 조회
        img_field  = clean_data['upimg'] #업로드된 파일을 조회
        print(img_field, type(img_field))
        print(img_field.image.width, img_field.image.height, img_field.image.format, img_field.name) #ImageField.name: 파일명
        form = 'id'
        image = Image.open(img_field) # 이미지 c로딩
        image_arr = np.array(image)
        
        kor_model = ApiConfig.model
        eng_model = ApiConfig.eng_model
        
        # img detect
        print('load 시간:', time() - start_time)
        start_time = time()
        
        detect_result = func_ver2.detect_postprocess(kor_model.detect(image_arr))
        print('detect 시간:', time() - start_time)
        start_time = time()
        
        # 데이터 분류 , form에 양식 넣기
        bbox_class, model_type = func_ver2.bbox_classification(image_arr, detect_result, form = form)
        
        # 글씨 분류
        rec_result = func_ver2.data_recognition(image_arr, bbox_class, model_type, kor_model, eng_model)
        print('reconize 시간:', time() - start_time)
        start_time = time()
        
        # 후처리 - 모델에 따라 customize 필요 
        result, pre_result = func_ver2.recog_postprocess(rec_result, need_address = True, class_result = form)
        print('후처리 시간:', time() - start_time)
        start_time = time()
        
        blur_img = func_ver2.blur_image(image_arr, detect_result)
        img = Image.fromarray(blur_img)
        img = img.resize((410, 260))
        blur_url = './img/img/blur'+str(random.random())+'.png'
        img.save(blur_url)
        result['url'] = blur_url[1:]
        result['pre_result'] = pre_result
        result['form'] = form
        
        return HttpResponse(json.dumps(result))

@csrf_exempt # form post 요청을 받을 때 csrf 토큰없이 요청할 수 있도록 처리.
def predict2(request):
    # 요청파라미터 - text: request.POST, file: request.FILES
    start_time = time()
    form = forms.UploadForm(request.POST, request.FILES)
    if form.is_valid(): #요청파라미터 검증. True: 검증 성공, False: 검증 실패
        clean_data = form.cleaned_data #Form에서 직접 값을 조회할 수 없다. form.cleaned_data: 검증을 통과한 
                                       #요청파라미터들을 딕셔너리로 반환. 이 딕셔너리를 이용해 조회
        img_field  = clean_data['upimg'] #업로드된 파일을 조회
        print(img_field, type(img_field))
        print(img_field.image.width, img_field.image.height, img_field.image.format, img_field.name) #ImageField.name: 파일명
        form = 'foreign'
        image = Image.open(img_field) # 이미지 c로딩
        image_arr = np.array(image)
#         image_arr = cv2.cvtColor(image_arr, cv2.COLOR_RGB2GRAY)
        
        kor_model = ApiConfig.model
        eng_model = ApiConfig.eng_model
        print('load 시간:', time() - start_time)
        start_time = time()
        
        # img detect
        detect_result = func_ver2.detect_postprocess(kor_model.detect(image_arr))
        print('detect 시간:', time() - start_time)
        start_time = time()
        # 데이터 분류 , form에 양식 넣기
        bbox_class, model_type = func_ver2.bbox_classification(image_arr, detect_result, form = form)
        
        # 글씨 분류
        rec_result = func_ver2.data_recognition(image_arr, bbox_class, model_type, kor_model, eng_model)
        print('reconize 시간:', time() - start_time)
        start_time = time()
        
        # 후처리 - 모델에 따라 customize 필요 
        result, pre_result = func_ver2.recog_postprocess(rec_result, need_address = True, class_result = form)
        print('후처리 시간:', time() - start_time)
        start_time = time()
        
        blur_img = func_ver2.blur_image(image_arr, detect_result)
        img = Image.fromarray(blur_img)
        img = img.resize((410, 260))
        blur_url = './img/img/blur'+str(random.random())+'.png'
        img.save(blur_url)
        result['url'] = blur_url[1:]
        result['pre_result'] = pre_result
        result['form'] = form
        
        return HttpResponse(json.dumps(result))

api/templates/api/.ipynb_checkpoints/request-checkpoint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src='https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js'></script>
    <script>        
        $(document).ready(function() {
            $('#reqBtn').on('click', function() {
                // $('#upimg')[0] : jQuery에서 객체 추출 : <input type=file ... >
                //              .files : 선택한 파일 => 배열(FileList)로 반환 [File객체]
                // 
                fileList = $('#upimg')[0].files
                if (fileList.length == 0) { //사용자가 파일을 선택했는지 확인
                    alert("이미지 파일을 선택하세요.")
                    return
                }
                upImg = fileList[0]  //File 객체 반환. File.type : image/jpg - mime type 반환. image가 아니면 전송안되도록 처리.
                if (!upImg.type.startsWith('image')) {
                    alert("이미지 파일이 아닙니다.")
                    return 
                }

                // FormData() : 요청파라미터를 저장하는 객체
                // append(name, value) 로 저장
                reqData = new FormData()
                reqData.append('upimg', upImg)
                console.log(reqData);
                
                $.ajax({
                    "url":"http://58.181.51.162:5500/api/predict",
                    "method":"post",
                    "data":reqData, //요청파라미터 - 이미지
                    'dataType':'json', //응답으로 받은 json 문자열을 javascript 객체로 변화해서 success함수에 전달.
                    "processData":false, //데이터를 문자열로 바꿀지 여부. true: 문자열
                    "contentType":false, //multpart/form-data로 전송
                    "success": function(res) {
                        // alert(res.img_url)
                        console.log(res);
                        html = `
                            <ul>
                                <h3>인식 결과</h3>
                                ${res.pre_result}<br>
                                <h3>후처리 결과</h3>
                                이름: ${res.name}<br>
                                주민등록번호: ${res.id_number}<br>
                                주소: ${res.address}<br>
                                발급일자: ${res.issue_date}<br>
                                발급자: ${res.issuer}<br><br>
                                이미지 속 인식된 텍스트<br><b><img src="${res.url}" /></br>
                            </ul>`
                        
                        

                        $('#result').html(html)
                    },
                    "error":function(e){
                        alert(e)
                    }
                       
                });
            });
        })
    </script>
    <script>        
        $(document).ready(function() {
            $('#reqBtn_f').on('click', function() {
                // $('#upimg')[0] : jQuery에서 객체 추출 : <input type=file ... >
                //              .files : 선택한 파일 => 배열(FileList)로 반환 [File객체]
                // 
                fileList = $('#upimg')[0].files
                if (fileList.length == 0) { //사용자가 파일을 선택했는지 확인
                    alert("이미지 파일을 선택하세요.")
                    return
                }
                upImg = fileList[0]  //File 객체 반환. File.type : image/jpg - mime type 반환. image가 아니면 전송안되도록 처리.
                if (!upImg.type.startsWith('image')) {
                    alert("이미지 파일이 아닙니다.")
                    return 
                }

                // FormData() : 요청파라미터를 저장하는 객체
                // append(name, value) 로 저장
                reqData = new FormData()
                reqData.append('upimg', upImg)
                console.log(reqData);
                
                $.ajax({
                    "url":"http://58.181.51.162:5500/api/predict2",
                    "method":"post",
                    "data":reqData, //요청파라미터 - 이미지
                    'dataType':'json', //응답으로 받은 json 문자열을 javascript 객체로 변화해서 success함수에 전달.
                    "processData":false, //데이터를 문자열로 바꿀지 여부. true: 문자열
                    "contentType":false, //multpart/form-data로 전송
                    "success": function(res) {
                        // alert(res.img_url)
                        console.log(res);
                        html = `
                            <ul>
                                <h3>인식 결과</h3>
                                ${res.pre_result}<br>
                                <h3>후처리 결과</h3>
                                이름: ${res.name}<br>
                                주민등록번호: ${res.id_number}<br>
                                나라: ${res.country}<br>
                                발급일자: ${res.issue_date}<br>
                                발급자격: ${res.qualification}<br><br>
                                이미지 속 인식된 텍스트<br><b><img src="${res.url}" /></br>
                            </ul>`
                        $('#result').html(html)
                    },
                    "error":function(e){
                        alert(e)
                    }
                });
            });
        })
    </script>
</head>
<body>

    <input type='file' name='upimg' id='upimg'>
    <button type='button' id='reqBtn'>주민등록증 예측</button>
    <button type='button' id='reqBtn_f'>외국인등록증 예측</button>
    
    <div id='result'>
        
    </div>
</body>
</html>

api/templates/api/.ipynb_checkpoints/request2-checkpoint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method='post' action='{% url "api:predict2" %}' enctype="multipart/form-data">
        {% csrf_token %}
        <input type='file' name='upimg'>
        <button type='submit'>예측</button>
    </form>
</body>
</html>

api/templates/api/.ipynb_checkpoints/response2-checkpoint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>예측결과</h2>
    Class: {{result}}<br>
    확률: {{pred}}<br>
    <img src='{{img_url}}' width='500'>

</body>
</html>

api/templates/api/request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src='https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js'></script>
    <script>        
        $(document).ready(function() {
            $('#reqBtn').on('click', function() {
                // $('#upimg')[0] : jQuery에서 객체 추출 : <input type=file ... >
                //              .files : 선택한 파일 => 배열(FileList)로 반환 [File객체]
                // 
                fileList = $('#upimg')[0].files
                if (fileList.length == 0) { //사용자가 파일을 선택했는지 확인
                    alert("이미지 파일을 선택하세요.")
                    return
                }
                upImg = fileList[0]  //File 객체 반환. File.type : image/jpg - mime type 반환. image가 아니면 전송안되도록 처리.
                if (!upImg.type.startsWith('image')) {
                    alert("이미지 파일이 아닙니다.")
                    return 
                }

                // FormData() : 요청파라미터를 저장하는 객체
                // append(name, value) 로 저장
                reqData = new FormData()
                reqData.append('upimg', upImg)
                console.log(reqData);
                
                $.ajax({
                    "url":"http://58.181.51.162:5500/api/predict",
                    "method":"post",
                    "data":reqData, //요청파라미터 - 이미지
                    'dataType':'json', //응답으로 받은 json 문자열을 javascript 객체로 변화해서 success함수에 전달.
                    "processData":false, //데이터를 문자열로 바꿀지 여부. true: 문자열
                    "contentType":false, //multpart/form-data로 전송
                    "success": function(res) {
                        // alert(res.img_url)
                        console.log(res);
                        html = `
                            <ul>
                                <h3>인식 결과</h3>
                                ${res.pre_result}<br>
                                <h3>후처리 결과</h3>
                                이름: ${res.name}<br>
                                주민등록번호: ${res.id_number}<br>
                                주소: ${res.address}<br>
                                발급일자: ${res.issue_date}<br>
                                발급자: ${res.issuer}<br><br>
                                이미지 속 인식된 텍스트<br><b><img src="${res.url}" /></br>
                            </ul>`
                        
                        

                        $('#result').html(html)
                    },
                    "error":function(e){
                        alert(e)
                    }
                       
                });
            });
        })
    </script>
    <script>        
        $(document).ready(function() {
            $('#reqBtn_f').on('click', function() {
                // $('#upimg')[0] : jQuery에서 객체 추출 : <input type=file ... >
                //              .files : 선택한 파일 => 배열(FileList)로 반환 [File객체]
                // 
                fileList = $('#upimg')[0].files
                if (fileList.length == 0) { //사용자가 파일을 선택했는지 확인
                    alert("이미지 파일을 선택하세요.")
                    return
                }
                upImg = fileList[0]  //File 객체 반환. File.type : image/jpg - mime type 반환. image가 아니면 전송안되도록 처리.
                if (!upImg.type.startsWith('image')) {
                    alert("이미지 파일이 아닙니다.")
                    return 
                }

                // FormData() : 요청파라미터를 저장하는 객체
                // append(name, value) 로 저장
                reqData = new FormData()
                reqData.append('upimg', upImg)
                console.log(reqData);
                
                $.ajax({
                    "url":"http://58.181.51.162:5500/api/predict2",
                    "method":"post",
                    "data":reqData, //요청파라미터 - 이미지
                    'dataType':'json', //응답으로 받은 json 문자열을 javascript 객체로 변화해서 success함수에 전달.
                    "processData":false, //데이터를 문자열로 바꿀지 여부. true: 문자열
                    "contentType":false, //multpart/form-data로 전송
                    "success": function(res) {
                        // alert(res.img_url)
                        console.log(res);
                        html = `
                            <ul>
                                <h3>인식 결과</h3>
                                ${res.pre_result}<br>
                                <h3>후처리 결과</h3>
                                이름: ${res.name}<br>
                                주민등록번호: ${res.id_number}<br>
                                나라: ${res.country}<br>
                                발급일자: ${res.issue_date}<br>
                                발급자격: ${res.qualification}<br><br>
                                이미지 속 인식된 텍스트<br><b><img src="${res.url}" /></br>
                            </ul>`
                        $('#result').html(html)
                    },
                    "error":function(e){
                        alert(e)
                    }
                });
            });
        })
    </script>
</head>
<body>

    <input type='file' name='upimg' id='upimg'>
    <button type='button' id='reqBtn'>주민등록증 예측</button>
    <button type='button' id='reqBtn_f'>외국인등록증 예측</button>
    
    <div id='result'>
        
    </div>
</body>
</html>

api/templates/api/request2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method='post' action='{% url "api:predict2" %}' enctype="multipart/form-data">
        {% csrf_token %}
        <input type='file' name='upimg'>
        <button type='submit'>예측</button>
    </form>
</body>
</html>

api/templates/api/response2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>예측결과</h2>
    Class: {{result}}<br>
    확률: {{pred}}<br>
    <img src='{{img_url}}' width='500'>

</body>
</html>